name: Coverage

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: greatwizard/coverage-diff-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
